# -*- mode: ruby -*-
# vi: set ft=ruby :
 
Vagrant.configure("2") do |config|
    
	config.ssh.forward_x11 = true


    config.vm.box = "precise64"
    config.vm.box_url = "http://files.vagrantup.com/precise64.box"

	config.vm.provision :shell, :path => "bootstrap.sh"

#    config.vm.network :private_network, ip: "192.168.33.101"
    config.vm.synced_folder "./", "/vagrant", id: "vagrant-root"
    config.vm.provision "shell", inline: "echo hello"

end
